import React, { Component } from 'react';

export default class Finance extends Component {
    render() {
        return(
            <div>
                this is the Finance
                <p>Hl</p>
                <p>Hl</p>
                <p>Hl</p>
                <p>Hl</p>
                <p>Hl</p>
                <p>Hl</p>
                <p>Hl</p>
                <p>Hl</p>
                <p>Hl</p>
                <p>Hl</p>
                <p>Hl</p>
                <p>Hl</p>
                <p>Hl</p>
                <p>Hl</p>
                <p>Hl</p>
                <p>Hl</p>
                <p>Hl</p>
                <p>Hl</p>
                <p>Hl</p>
                <p>Hl</p>
                <p>Hl</p>
                <p>Hl</p>
                <p>Hl</p>
                <p>Hl</p>
                <p>Hl</p>
                <p>Hl</p>
                <p>Hl</p>
                <p>Hl</p>
                <p>Hl</p>
                <p>Hl</p>
                <p>Hl</p>
                <p>Hl</p>
                <p>Hl</p>
                <p>Hl</p>
                <p>Hl</p>
                <p>Hl</p>
                <p>Hl</p>
                <p>Hl</p>
                <p>Hl</p>
                <p>Hl</p>
                <p>Hl</p>
                <p>Hl</p>
                <p>Hl</p>
                <p>Hl</p>
                <p>Hl</p>
                <p>Hl</p>
                <p>Hl</p>
                <p>Hl</p>
                <p>Hl</p>
                <p>Hl</p>
                <p>Hl</p>
                <p>Hl</p>
                <p>Hl</p>
                <p>Hl</p>
                <p>Hl</p>
                <p>Hl</p>
                <p>Hl</p>
                <p>Hl</p>
                <p>Hl</p>
                <p>Hl</p>
                <p>Hl</p>
                <p>Hl</p>
                <p>Hl</p>
                <p>Hl</p>
                <p>Hl</p>
                <p>Hl</p>
                <p>Hl</p>
                <p>Hl</p>
                <p>Hl</p>
                <p>Hl</p>
                <p>Hl</p>
                <p>Hl</p>
                <p>Hl</p>
                <p>Hl</p>
                <p>Hl</p>
                <p>Hl</p>
                <p>Hl</p>
                <p>Hl</p>
                <p>Hl</p>
                <p>Hl</p>
                <p>Hl</p>
                <p>Hl</p>
                <p>Hl</p>
                <p>Hl</p>
                <p>Hl</p>
                <p>Hl</p>
                <p>Hl</p>
                <p>Hl</p>
                <p>Hl</p>
                <p>Hl</p>
                <p>Hl</p>
                <p>Hl</p>
                <p>Hl</p>
                <p>bottom</p>
            </div>
        );
    }
}